version: "3"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data